version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password

  api:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
    environment:
      - VITE_API_URL="http://api:8000"
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.crt:/etc/nginx/conf.d/nginx.crt
      - ./nginx/nginx.key:/etc/nginx/conf.d/nginx.key      
    depends_on:
      - api
      - client
    ports:
      - "80:80"
      - "443:443"
